apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawlers-jobnagringa-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawlers-jobnagringa
  template:
    metadata:
      labels:
        app: crawlers-jobnagringa
    spec:
      containers:
        - name: crawlers-jobnagringa
          image: gcr.io/handy-outpost-423914-i4/crawlers.jobnagringa:v1
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__DefaultConnection
              value: "Server=10.104.240.3;Database=jobsdb;User Id=ijs;Password=localPass;"
---
apiVersion: v1
kind: Service
metadata:
  name: crawlers-jobnagringa-service
spec:
  type: LoadBalancer
  selector:
    app: crawlers-jobnagringa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80